# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: boletin-django-rf-aneachi
    container_name: boletin-django-rf-aneachi
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - boletin-django-rf_postgres_data:/var/lib/postgresql/data
#      - drf-tutorial_data_backups:/backups
    ports:
      - 5435:5432

volumes:
  boletin-django-rf_postgres_data:
#  drf-tutorial_data_backups:
